AJAX calls for last fm api
meeday/The-Music-App pull request #21
Opened 2020-04-30 21:34 UTC by drg0drg

2020-04-30 22:23 UTC, Goldenaries658 requested changes
Change classes to IDs for good practice as they will be unique. Please format before pushing.

2020-04-30 22:23 UTC, Goldenaries658 commented on index.html
> +            <input name="group1" type="radio" class="with-gap track-btn" checked />
```suggestion
            <input id="track-btn" name="group1" type="radio" class="with-gap" checked />
```

2020-04-30 22:23 UTC, Goldenaries658 commented on index.html
> +            <input name="group1" type="radio" class="with-gap album-btn" />
```suggestion
            <input id="album-btn" name="group1" type="radio" class="with-gap" />
```

2020-04-30 22:23 UTC, Goldenaries658 commented on index.html
> +            <input name="group1" type="radio" class="with-gap artist-btn" />
```suggestion
            <input id="artist-btn" name="group1" type="radio" class="with-gap" />
```

2020-04-30 22:23 UTC, Goldenaries658 commented on assets/script.js
> +    } else if ($('.artist-btn').is(':checked')) {
```suggestion
    if($('#track-btn').is(':checked')) {
        getTrackInfo(userInput);
    } else if ($('#album-btn').is(':checked')) {
        getAlbumInfo(userInput);
    } else if ($('#artist-btn').is(':checked')) {
```

2020-05-01 12:39 UTC, drg0drg commented on index.html
> +            <input name="group1" type="radio" class="with-gap track-btn" checked />
changed the class to id

2020-05-01 13:27 UTC, meeday approved these changes

2020-05-01 13:28 UTC, meeday approved these changes

2020-05-01 13:30 UTC, Goldenaries658 approved these changes

2020-05-01 13:30 UTC, merged